apiVersion: "kubeflow.org/v1"
kind: PyTorchJob
metadata:
  name: pytorch-single-node
  namespace: opendatahub
spec:
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          containers:
            - name: pytorch
              image: docker.io/kubeflowkatib/pytorch-mnist:v1beta1-45c5727
              command:
                - "python3"
                - "/opt/pytorch-mnist/mnist.py"
                - "--epochs=1"
                - "--lr=0.01"
                - "--batch-size=64"
              env:
                - name: PYTHONUNBUFFERED
                  value: "1"
              resources:
                requests:
                  cpu: 1
                  memory: 1Gi
                limits:
                  cpu: 2
                  memory: 2Gi
