apiVersion: "kubeflow.org/v1"
kind: PyTorchJob
metadata:
  name: pytorch-elastic-training
  namespace: opendatahub
spec:
  elasticPolicy:
    rdzvBackend: etcd
    minReplicas: 1
    maxReplicas: 4
    maxRestarts: 10
  pytorchReplicaSpecs:
    Worker:
      replicas: 2
      restartPolicy: OnFailure
      template:
        spec:
          containers:
            - name: pytorch
              image: docker.io/kubeflowkatib/pytorch-mnist:v1beta1-45c5727
              command:
                - "python3"
                - "/opt/pytorch-mnist/mnist.py"
                - "--epochs=1"
              env:
                - name: LOGLEVEL
                  value: INFO
              resources:
                requests:
                  cpu: 500m
                  memory: 512Mi
                limits:
                  cpu: 1
                  memory: 1Gi
